site_name: StrixEye
site_url: https://docs.strixeye.com
extra_css:
  - assets/stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/white.svg
  favicon: assets/images/purple.png
  font:
    text: Ubuntu
    code: Ubuntu mono

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Navigation
nav:
  - Welcome: index.md
  - Installation: installation.md
  - Configure Trigger and Integration: configure_trigger_integration.md
  - In-Depth Dashboard: 
      # - Dashboard: in-depth_dashboard/dashboard.md
      - Suspects: in-depth_dashboard/suspects.md
      - Suspicions: in-depth_dashboard/suspicions.md
      - Agents: in-depth_dashboard/agents.md
      - Domains: in-depth_dashboard/domains.md
  #     - Integrations: triggers/delete.md
  #     - Trigger Rules: triggers/delete.md
      - Users: in-depth_dashboard/users.md
      - Roles: in-depth_dashboard/roles.md
  #     - Activity Logs: triggers/delete.md
  #     - Profile: triggers/delete.md
  #     - Company Info: triggers/delete.md
  # - In-Depth Agent:
  #     - Cli: triggers/delete.md
  #     - Agent: triggers/delete.md
  # - Mirror Requests:
  #     - NGINX: triggers/delete.md
  #     - Apache: triggers/delete.md
  #     - IIS: triggers/delete.md
  #     - AWS Load Balancer: triggers/delete.md
  #     - Traefik: triggers/delete.md

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/strixeyecom
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/StrixEye
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/strixeye
